### ISSUE TITLE
Some search boxes do not work 

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/gwas-ui#350]
On this page: https://www.ebi.ac.uk/gwas/labs/downloads/summary-statistics, in the first table, typing in the Trait(s) box does not work.

**Comment by ljwh2** [comment]
Also, search box does not work for first author in studies table on any page

**Comment by ala-ebi** [comment]
@sajo-ebi please add firstAuthor search param to the search params for Study

**Comment by sajo-ebi** [comment]
@ala-ebi the 'firstAuthor' param has been added to Studies endpoint

**Comment by sprintell** [comment]
Done, waiting to be deployed

**Comment by sajo-ebi** [comment]
@ljwh2 Deployed in Dev [http://gwas-snoopy.ebi.ac.uk:9780/gwas](http://gwas-snoopy.ebi.ac.uk:9780/gwas)

**Comment by ljwh2** [comment]
Confirmed First author search now works

**Comment by ljwh2** [comment]
When searching by trait on the sumstats page: https://www.ebi.ac.uk/gwas/labs/downloads/summary-statistics I encountered an error on loading the page. Cleared the error and the table loaded without any data in the reported trait column.  Searching in the Trait(s) box produced the error again, but the search did work after clearing the error.![Screenshot 2023-06-21 at 19.27.08.png](https://images.zenhubusercontent.com/5e57ecb5d0668b3a20e94b9e/585752ef-505b-4a3d-b2bb-92551b77a0f6)

**Comment by ljwh2** [comment]
Confirmed reported traits are still not displayed in sumstats table (but I don't see the error message now)

**Comment by ljwh2** [comment]
We expect this will not happen in prod

**Comment by ljwh2** [comment]
First author search box still does not work

**Comment by ljwh2** [comment]
See also goci#1107

**Comment by ljwh2** [comment]
needs releasing

**Comment by ljwh2** [comment]
Now released
